### ISSUE TITLE
Re-publish package on NuGet

### ISSUE THREAD

**Issue by Piedone** [agriffard/TheClassLessTheme#16]
Same as for [TheBootstrapTheme](https://github.com/agriffard/TheBootstrapTheme/issues/16).

**Comment by wAsnk** [comment]
When should we expect it to be published on NuGet? @agriffard

**Comment by wAsnk** [comment]
It's up now [https://www.nuget.org/packages/TheClassLessTheme](https://www.nuget.org/packages/TheClassLessTheme)

**Comment by Piedone** [comment]
So it's only that the NuGet shield links to the wrong package from the Readme.

**Comment by Piedone** [comment]
Thanks!
